In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input, Dense, Flatten, SimpleRNN
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

N = number of samples  
T = sequence length  
D = number of input features  
M = number of hidden units  
K = number of output units


In [2]:
#some data
N=1
T=10
D=3
K=2
X=np.random.randn(N,T,D)

In [3]:
M=5
i=Input(shape=(T,D))
x=SimpleRNN(M)(i)
x=Dense(K)(x)
model=Model(i,x)

In [5]:
Yhat=model.predict(X)
print(Yhat)

1/1 [==============================] - 0s 39ms/step
[[ 0.3902549 -0.6023844]]


here the values wont make sense its just for sanity testing and undertanding the rnn 

In [6]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.layers[1].get_weights()

[array([[-0.54372066,  0.4035254 ,  0.4197561 ,  0.6702351 ,  0.35536247],
        [ 0.5276417 ,  0.0191769 ,  0.242562  ,  0.33618492,  0.04705995],
        [-0.07148343, -0.34342706,  0.6613652 , -0.50900614,  0.8236061 ]],
       dtype=float32),
 array([[ 0.6575103 , -0.13291807, -0.59840655, -0.433106  ,  0.06589173],
        [-0.28618214, -0.3380685 ,  0.33169562, -0.7272118 ,  0.40614098],
        [-0.5172418 ,  0.09003003, -0.385112  , -0.38066864, -0.65660906],
        [-0.4661347 , -0.14073884, -0.6189569 ,  0.2746628 ,  0.55169165],
        [ 0.03097378, -0.9165858 ,  0.02164863,  0.25146335, -0.30855885]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [8]:
a,b,c=model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [9]:
Wx,Wh,bh=model.layers[1].get_weights()
Wo,bo=model.layers[2].get_weights()

In [11]:
h_last=np.zeros(M)
x=X[0]
Yhats=[]
for t in range (T):
    h=np.tanh(x[t].dot(Wx)+h_last.dot(Wh)+bh)
    y=h.dot(Wo)+bo
    Yhats.append(y)
    h_last=h
print(Yhats[-1])

[ 0.39027161 -0.60236823]
